// utils/detailMoods.ts
export const DETAIL_MOODS: Record<string, string[]> = {
  happy: [
    "Hào hứng",
    "Vui vẻ",
    "Phấn khởi",
    "Biết ơn",
    "Tự hào",
    "Thoải mái",
    "Tràn đầy năng lượng",
    "Lạc quan",
    "Yêu đời",
    "Được truyền cảm hứng",
  ],

  peaceful: [
    "Thư giãn",
    "Bình yên",
    "Cân bằng",
    "Nhẹ nhõm",
    "An toàn",
    "Hài lòng",
    "Tĩnh lặng",
    "Dễ chịu",
    "Không áp lực",
    "Thả lỏng",
  ],

  neutral: [
    "Bình thường",
    "Ổn định",
    "Không rõ ràng",
    "Lửng lơ",
    "Không có gì đặc biệt",
    "Thiếu cảm xúc",
    "Tạm ổn",
    "Trung lập",
  ],

  sad: [
    "Buồn bã",
    "Cô đơn",
    "Tổn thương",
    "Thất vọng",
    "Mệt mỏi",
    "Trống rỗng",
    "Chán nản",
    "Yếu đuối",
    "Muốn khóc",
    "Mất động lực",
    "Kiệt sức",
    "Đuối năng lượng",
    "Không muốn làm gì",
    "Burnout",
  ],

  anxious: [
    "Lo lắng",
    "Lo sợ",
    "Bất an",
    "Căng thẳng",
    "Áp lực",
    "Bồn chồn",
    "Hồi hộp",
    "Sợ hãi",
    "Hoang mang",
    "Không kiểm soát được",
  ],
};
